name: "Build keyboard with @keymanapp/kmc"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.2
    
    - name: build with npx
      shell: bash
      run: |
        npx --package @keymanapp/kmc@17.0.302-beta kmc build . --for-publishing

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build
