name: "Build keyboard with @keymanapp/kmc"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # - name: Setup Node.js environment
    #   uses: actions/setup-node@v4.0.2
    #   with:
    #     # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    #     node-version: ">=18.0.0"
    
    - name: build with npx
      shell: bash
      run: |
        npx --package @keymanapp/kmc@17.0.301 build . --for-publishing

    - name: Archive artifacts
      uses: actions.upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build
